# Generated by Django 2.0.5 on 2019-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('name', models.TextField(verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
